### ISSUE TITLE
pretrained weights 

### ISSUE THREAD

**Issue by shulang97** [MahmoudWahdan/Siamese-Sentence-Similarity#3]
Dear Mr.Wahdan,

We are currently working on a nlp project and read your paper "Siamese Recurrent Architectures for Learning Sentence Similarity". We think your model is super impressive and powerful! As we want to train and test on a new dataset, could you please upload the pretrain weights? 

Thank you so much!

**Comment by MahmoudWahdan** [comment]
Dear @shulang97, Thank you for your interest towards my repo.
Actually, This is my implementation and I'm not one of the paper's authors. Here, following the paper I'm using Word2Vec (download from https://code.google.com/archive/p/word2vec/). It's the only pretrained vectors used in the model.
You also may be interested in using BERT or any transformer architecture instead of RNNs in the Siamese architecture. I'll try to cover this implementation in the repo as well.
